apiVersion: v1
kind: Pod
metadata:
  name: "busybox"
  namespace: default
  labels:
    app: "busybox"
spec:
  containers:
  - name: busybox
    image: busybox
    resources:
      limits:
        cpu: 200m
        memory: 500Mi
      requests:
        cpu: 100m
        memory: 200Mi
    ports:
    - containerPort:  80
      name:  http
    env:
    - name: ASPNETCORE_ENVIRONMENT
      value: DEVELOPMENT
    command: ["/bin/bash"]
    args: ["-c", "while true; do echo 'busybox running'; sleep 10;done"]